language: elixir

cache:
  directories:
    - $HOME/.mix
    - _build
    - deps

elixir:
  - 1.10.0

otp_release:
  - 22

env:
  - MIX_ENV=test

script:
  - mix compile --force --warnings-as-errors
  - mix format --check-formatted
  - mix credo
  - mix do ecto.create, ecto.migrate
  - mix coveralls.travis
